### PR TITLE
MustBeNoExceptVoidFunctor should depend on the template type parameter to avoid being evaluated too early

### LINKED ISSUE #9559: Can't build a RNW project with Visual Studio 2022 17.1
### Problem Description

Since I upgraded my Visual Studio 2022 installation to 17.1, I can't compile anymore any React Native for Windows project. I always get the following error during the build process of the Microsoft.ReactNative project:

C:\src\VS2022\node_modules\react-native-windows\Mso\dispatchQueue\dispatchQueue.h(728,17): error C2607: static assertion failed
C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(486,5): error MSB4181: The "CompileXaml" task returned false but did not log an error.

The same project compiled with Visual Studio 2019 builds fine.

### Steps To Reproduce

 1. Create a new RNW project based on RN 0.67
 2. Open the solution inside the windows folder with Visual Studio 2022 17.1
 3. Build the Microsoft.ReactNative project

### Expected Results

The solution can be compiled without errors

### CLI version

6.4.0

### Environment

```markdown
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 2.09 GB / 15.60 GB
  Binaries:
    Node: 14.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17134.0, 10.0.17763.0, 10.0.18362.0, 10.0.19041.0, 10.0.22000.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32126.315 (Visual Studio Enterprise 2019), 17.2.32210.308 (Visual Studio Enterprise 2022), 17.1.32210.238 (Visual Studio Enterprise 2022)
  Languages:
    Java: 11.0.14 - C:\Program Files\Microsoft\jdk-11.0.14.9-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.2 => 0.67.2
    react-native-windows: 0.67.1 => 0.67.1
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

### Snack, code example, screenshot, or link to a repository

_No response_

### PR DESCRIPTION
**Pull request by asklar**
## Description

Fixes #9559 

### Type of Change
- Bug fix (non-breaking change which fixes an issue)

### Why
VS 17.1 introduces stricter requirements on `static_assert`, which are causing a build break in the M.RN project. This fixes the previously invalid C++ code.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/9562)

### CODE REVIEW

File: vnext/Mso/dispatchQueue/dispatchQueue.h [hunk 1]
```diff
@@ -723,9 +723,14 @@ inline DispatchTaskImpl<TInvoke, TOnCancel>::~DispatchTaskImpl() noexcept {
   }
 }
 
+namespace details {
```
Comment (NikoAri) [inline vnext/Mso/dispatchQueue/dispatchQueue.h:726]: >details [](http://example.com/codeflow?start=10&length=7)

(nit) can you pascal-case this namespace

**Review by NikoAri — APPROVED** [review]
:shipit:

**Review by acoates-ms — APPROVED** [review]

**Comment by burtonrodman** [comment]
any word on what versions this will be backported to?  I am currently stuck on 0.64.x due to touch handling change in 0.65+ breaking our Canvas touch drawing.  i was able to manually patch this change into my node_modules to keep working today, but that obviously isn't a long term solution.

Thanks!

**Comment by asklar** [comment]
currently no plans to backport, this would go into 0.69; we currently don't _officially_ support vs2022 (e.g. we don't target the vc143 package, or c++20, etc. as there is more work involved), so this is more of a future protection.

**Comment by mikehardy** [comment]
In case anyone else needs to integrate this temporarily, it works great for me as-is from the PR diff as I'm updating react-native-device-info module and didn't want to revert my windows VM toolchain after updating it...

Here it is in patch-package form, gunzip it and drop it in `patches/` after integrating patch-package per instructions in that repo
[react-native-windows+0.67.3.patch.gz](https://github.com/microsoft/react-native-windows/files/8188418/react-native-windows%2B0.67.3.patch.gz)

**Comment by Shidouuu** [comment]
Thank you Anki guy
