### PR TITLE
Fix template specialization error in FrameworkElementViewManager.cpp

### PR DESCRIPTION
**Pull request by christophpurrer**
Does not compile with Clang 9.0.1 or with Clang 10.0.0
```
react-native-windows\vnext\ReactUWP\Views\FrameworkElementViewManager.cpp:41:8: error: class template specialization of 'json_type_traits' must occur at global scope
struct json_type_traits<winrt::react::uwp::AccessibilityAction> {
       ^
buck-out/gen/ec45211b/third-party/microsoft-fork-of-react-native/react-native-windows_MicrosoftReactNativeWindows#private-headers,windows-x86_64\Utils/PropertyHandlerUtils.h:55:8: note: explicitly specialized declaration is here
struct json_type_traits;
       ^
react-native-windows\vnext\ReactUWP\Views\FrameworkElementViewManager.cpp:57:8: error: class template specialization of 'json_type_traits' must occur at global scope
struct json_type_traits<winrt::IVector<winrt::react::uwp::AccessibilityAction>> {
       ^
buck-out/gen/ec45211b/third-party/microsoft-fork-of-react-native/react-native-windows_MicrosoftReactNativeWindows#private-headers,windows-x86_64\Utils/PropertyHandlerUtils.h:55:8: note: explicitly specialized declaration is here
struct json_type_traits;
```

It might not be desirable having templates in the global namespace, but this changes is at least consistent with usage in other files as: https://github.com/microsoft/react-native-windows/blob/master/vnext/ReactUWP/Views/FlyoutViewManager.cpp#L52-L67

## Test plan
Compiles with Clang 9.0.1
Compiles with VS 2019

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/4478)

### CODE REVIEW

**Comment by vmoroz** [comment]
It is rather unexpected to have the `json_type_traits` type in the global namespace.
Thank you for the fix!
