### ISSUE TITLE
Re-enable warning C4103 - Desktop solution fails to build using Visual Studio 16.9.

### ISSUE THREAD

**Issue by JunielKatarn** [microsoft/react-native-windows#7323]
## Environment
Run the following in your terminal and copy the results here.
1. Visual Studio `16.9`
2. Yarn `1.22.10`

- Target Platform Version(s): `10.0.18362`
What device(s) are you targeting? Choose any from Desktop, Xbox, Hololens)
- Target Device(s): `Desktop`
Which version of Visual Studio are you using? Specify Visual Studio 2017 or Visual Studio 2019
- Visual Studio Version: `16.9`
Which build configuration are you running? Choose from Debug, DebugBundle, Release, ReleaseBundle 
- Build Configuration: `Debug`

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. `yarn`
2. `yarn build`
3. `cd vnext`
4. `nuget restore ReactWindows-Desktop.sln`
5. `msbuild Desktop.UnitTests`

## Expected Results
Describe what you expected to happen.

Build succeeds.

## Actual Results
MSBuild fails with output:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\system_error(18,1): error C2220: the following warning is treated as an error [vnext\Desktop.UnitTests\React.Windows.Desktop.UnitTests.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\system_error(18,1): warning C4103: alignment changed after including header, may be due to missing #pragma pack(pop) [vnext\Desktop.UnitTests\React.Windows.Desktop.UnitTests.vcxproj]
```

**Comment by JunielKatarn** [comment]
Mitigated by #7319.

**Comment by asklar** [comment]
The warning seems to indicate we might have undefined behavior which could result in unreliable tests, we should figure out the right longer term fix.

**Comment by JunielKatarn** [comment]
Re-assigning to test maintainer.
