### ISSUE TITLE
X64 Debug Publish build broken

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#8671]
### Problem Description

From the [Publish build logs](https://dev.azure.com/microsoft/ReactNative/_build/results?buildId=39288320&view=logs&j=6be7cc23-915a-5aa5-0416-7f12ed4ab00f&t=04a8877e-7a83-5b19-7777-6df488eca3c5):

`vnext\Shared\Utils.cpp(7,10): Error C1083: Cannot open include file: 'DesktopWindowBridge.h': No such file or directory`

### Steps To Reproduce

See https://dev.azure.com/microsoft/ReactNative/_build/results?buildId=39288320&view=logs&j=6be7cc23-915a-5aa5-0416-7f12ed4ab00f&t=04a8877e-7a83-5b19-7777-6df488eca3c5

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

**Comment by jonthysell** [comment]
@mganandraj This broke after your changes in PR #8615. Can you look into this?

**Comment by jonthysell** [comment]
Looks like the failure is in Microsoft.ReactNative.ComponentTests

**Comment by jonthysell** [comment]
I think I've got it. PR soon.

**Comment by jonthysell** [comment]
I can get x64 building, but not x86 (which has been disabled, and I'm trying to re-enable so bugs like this don't get in again).
