### PR TITLE
Make JSValueReader.h compile with Clang [RFC]

### PR DESCRIPTION
**Pull request by christophpurrer**
I have spent quite some time on this but I can't make it compile with Clang 9.0.1 or Clang 10.0.0 as a static assert prevents compilation.
```
In file included from react-native-windows_MicrosoftReactNativeCxx_targetWindows#header-mode-symlink-tree-only,headers\NativeModules.h:8:
react-native-windows_MicrosoftReactNativeCxx_targetWindows#header-mode-symlink-tree-only,headers/JSValueReader.h:160:5: error: static_assert failed "Unsupported char type"
    static_assert(false, "Unsupported char type");
    ^             ~~~~~
1 error generated.
```
This happens on https://github.com/microsoft/react-native-windows/blob/react-native-windows_v0.60.0-vnext.133/vnext/Microsoft.ReactNative.Cxx/JSValueReader.h - but it seems the same code is still in master

The problem happens here > https://github.com/microsoft/react-native-windows/blob/master/vnext/Microsoft.ReactNative.Cxx/JSValueReader.h#L156

But we only pass in ```char``` and ```wchar_t```  > https://github.com/microsoft/react-native-windows/blob/master/vnext/Microsoft.ReactNative.Cxx/JSValueReader.h#L168-L192

I looked at https://docs.microsoft.com/en-us/cpp/build/reference/zc-wchar-t-wchar-t-is-native-type?view=vs-2019 but it did help me either.

Also tried to treat ```unsigned short as wchar_t```
https://docs.microsoft.com/en-us/cpp/cpp/fundamental-types-cpp?view=vs-2019 ... no luck

The ```basic_string_convert``` is only used with ```char``` and ```wchar_t``` and the only arguments passed in are ```Int64_t``` and ```double``` so maybe we can just use the built-in ```std::to_string``` / ```std::to_wstring``` functions instead

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/4481)

### CODE REVIEW

**Comment by vmoroz** [comment]
The `std::to_string` and `std::to_wstring` give us a different result. It causes the unit test to fail in CI. I am going to look into it. I did not write the `basic_string_convert` function from scratch: it is 'borrowed' from C++/WinRT. They may have a better version now.

How can I repro the issue that you have? What would be the simplest steps to compile this code with Clang? Sorry, I just never compiled Windows code with Clang.

It would be great if you could help us setup the Clang build in our CI loop. In that case we would be more proactive for issues like this one.

**Comment by vmoroz** [comment]
I wish I had a better error message for the failing test. The originally used Catch2 was giving better error messages than GTest in such cases. The difference is that `std::to_string` adds several zeroes in the end of string and we better not to use it. See: https://en.cppreference.com/w/cpp/string/basic_string/to_string
```
std::cout: 23.43
to_string: 23.430000
```
The part that I 'borrowed' from the `winrt::impl::hstring_convert` did not change. The compilation is failing in the part that I added in the end.

Recently I have added `JSConverter` inside of the `JSValue.cpp`. I am going to extract it into its own `JSConverter.h` and use it for both `JSValueReader.h` and `JSValue`. This way we are going to have more consistent conversion story and no template 'magic'.

File: vnext/Microsoft.ReactNative.Cxx/JSValueReader.h [hunk 1]
```diff
@@ -166,10 +145,10 @@ inline void ReadValue(IJSValueReader const &reader, /*out*/ std::string &value)
       value = reader.GetBoolean() ? "true" : "false";
       break;
     case JSValueType::Int64:
-      value = basic_string_convert<char>(reader.GetInt64());
+      value = std::to_string(reader.GetInt64());
       break;
     case JSValueType::Double:
-      value = basic_string_convert<char>(reader.GetDouble());
+      value = std::to_string(reader.GetDouble());
```
Comment (vmoroz) [inline vnext/Microsoft.ReactNative.Cxx/JSValueReader.h:151]: Please replace it with the following code to make the unit test to pass:
``` C++
{
      std::stringstream ss;
      ss << value;
      value = ss.str();
      break;
}
```

File: vnext/Microsoft.ReactNative.Cxx/JSValueReader.h [hunk 2]
```diff
@@ -186,10 +165,10 @@ inline void ReadValue(IJSValueReader const &reader, /*out*/ std::wstring &value)
       value = reader.GetBoolean() ? L"true" : L"false";
       break;
     case JSValueType::Int64:
-      value = basic_string_convert<wchar_t>(reader.GetInt64());
+      value = std::to_wstring(reader.GetInt64());
       break;
     case JSValueType::Double:
-      value = basic_string_convert<wchar_t>(reader.GetDouble());
+      value = std::to_wstring(reader.GetDouble());
```
Comment (vmoroz) [inline vnext/Microsoft.ReactNative.Cxx/JSValueReader.h:171]: Please replace it with the following code to make the unit test to pass:
``` C++
{
      std::wstringstream ss;
      ss << reader.GetDouble();
      value = ss.str();
      break;
}
```

**Comment by vmoroz** [comment]
@christophpurrer please see my suggested fixes for the conversions from `double`. It should fix the test and unblock the PR merge. For the long term solution I have created #4488 which hopefully will be addressed soon.

File: vnext/Microsoft.ReactNative.Cxx/JSValueReader.h (hunk 2 above)
Comment (christophpurrer) [reply vnext/Microsoft.ReactNative.Cxx/JSValueReader.h:173]: I have tried, but at least for me this leads to another error:
```
JSValueReader.h:182:5: error: cannot jump from switch statement to this case label
    default:
    ^
```
I am trying another approach ...

File: vnext/Microsoft.ReactNative.Cxx/JSValueReader.h (hunk 1 above)
Comment (vmoroz) [reply vnext/Microsoft.ReactNative.Cxx/JSValueReader.h:151]: It requires use of the curly braces as in the code snippet. I.e.
``` C++
case JSValueType::Double: {
  std::stringstream ss;
  ss << reader.GetDouble();
  value = ss.str();
  break;
}
```

Comment (christophpurrer) [reply vnext/Microsoft.ReactNative.Cxx/JSValueReader.h:151]: I apologize. I didn't see the ```{``` and ```}``` initially.
Just for the reference it is https://stackoverflow.com/a/92439

But even correctly applying the suggestion would not have made my compiler happy:
```
JSValueReader.h:180:13: error: no viable overloaded '='
      value = ss.str();
      ~~~~~ ^ ~~~~~~~~
```
