### ISSUE TITLE
NativeAnimatedModule.getValue is not a function

### ISSUE THREAD

**Issue by Abhishe08k** [microsoft/react-native-windows#10287]
### Problem Description

We have recently upgraded react native Windows version to 0.63.4 to 0.68.6.
We have started facing this issue after the upgrade. After launching the application if I click a button, I started getting error "NativeAnimatedModule.getValue is not a function". Attached the image. 

![image](https://user-images.githubusercontent.com/109737224/180208074-07f9d6a4-2cec-44bd-9079-55aedee20001.png)

Probable Fix :
The issue is within the file "NativeAnimatedHelper.js". In line no 51, below line is getting executed.
NativeAnimatedModule.getValue(tag, saveValueCallback);
 
If I prohibit the application to execute this line by wrapping it in the condition that should not be true in my case, i am no more getting this error. And everything is working as expected.
 
if (Platform.OS === 'android'){
        NativeAnimatedModule.getValue(tag, saveValueCallback);
      }
      

### Steps To Reproduce

1. Open Application 
2. Click a button
3. Screen goes blank with the error "NativeAnimatedModule.getValue is not a function".

### Expected Results

There should not be any error thrown and behave exactly as it was behaving in version 0.63.4.
The issue is getting reproduced after we upgraded the version to 0.68.6.

Probable Fix :
The issue is within the file "NativeAnimatedHelper.js". In line no 51, below line is getting executed.
NativeAnimatedModule.getValue(tag, saveValueCallback);
 
If I prohibit the application to execute this line by wrapping it in the condition that should not be true in my case, i am no more getting this error. And everything is working as expected.
 
if (Platform.OS === 'android'){
        NativeAnimatedModule.getValue(tag, saveValueCallback);
      }

### CLI version

7.0.3

### Environment

```markdown
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 2.05 GB / 15.73 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32602.291 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.0.0 => 18.2.0
    react-native: ^0.68.2 => 0.68.2
    react-native-windows: ^0.68.6 => 0.68.9
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Device(s)

Desktop

**Comment by asklar** [comment]
@Abhishe08k are you trying to use Fabric? if so, that isn't yet working for Windows.
@acoates-ms does this look familiar?

**Comment by Abhishe08k** [comment]
> @Abhishe08k are you trying to use Fabric? if so, that isn't yet working for Windows. @acoates-ms does this look familiar?

@asklar , I am not using Fabric. I was using "react-native-screens" (2.11.0.) It does not support Fabric.
Today, i have taken the latest version of "react-native-screens"(3.15.0) that supports Fabric. But enabling/disabling fabric has not helped either. Getting the error irrespective of whether i enable/disable fabric.

**Comment by asklar** [comment]
I see, I recommend seeking support on the [react-native-screens repo](https://github.com/software-mansion/react-native-screens ), as it's possible that that module doesn't work well on Windows. CC @chiaramooney  in case she's seen this issue before.

**Comment by chiaramooney** [comment]
@asklar @Abhishe08k We have had issues in the past with the current partial Windows implementation for screen but I don't think I've seen this issue specifically. I'll look into it and see what I can find.

**Comment by chiaramooney** [comment]
@Abhishe08k So we know that 0.68 apps in general are not hitting this issue. It may be that something has gone wrong in your upgrade process. 63 -> 68 is a big jump. I would suggest upgrading incrementally through the versions to see where the error appears for you.

**Comment by Abhishe08k** [comment]
@chiaramooney , @asklar  Thank you for looking into this issue. After I changed the RNW version to 0.68.12(from 0.68.6) and upgrade the nuget version of my project to 0.68.12 as well, I am no more hitting this issue.

Thanks again for your time.
