### PR TITLE
Add GetFacebookReactInstance

### PR DESCRIPTION
**Pull request by ZihanChen-MSFT**
To get `facebook::react::Instance` from `uwp::Instance`

The reason not to do this directly in client application is, it requires the client application to include too many header files that are not designed to be included out side of ReactUWP, and it requires the client application to do too many configuration in its vcxproj file, which is not practical for consumers.

An `uwp::Instance` is needed for turbo module users for registering native module implementations.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-windows/pull/3782)

### CODE REVIEW

**Comment by JunielKatarn** [comment]
Why `GetFacebookReactInstance` and not `GetReactInstance`?

**Comment by ZihanChen-MSFT** [comment]
> Why `GetFacebookReactInstance` and not `GetReactInstance`?

I am going to say `facebook::react::Instance` in this way

File: vnext/ReactUWP/TurboModule/TurboModuleUtils.cpp [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+#include <ReactUWPABI.h>
+#include <TurboModuleUtils.h>
+#include "../ABI/Instance_rt.h"
+
+namespace react::uwp {
+
+std::shared_ptr<facebook::react::Instance> __cdecl GetFacebookReactInstance(
+    const winrt::react::uwp::Instance &uwpInstance) {
+  winrt::com_ptr<ABI::react::uwp::IInstance> abiIInstance;
+  winrt::copy_to_abi(uwpInstance, *abiIInstance.put_void());
```
Comment (licanhua) [inline vnext/ReactUWP/TurboModule/TurboModuleUtils.cpp]: Please don't use abi interface anymore.

I didn't do the testing, but I think you should use winrt::get_self.

if (auto self = winrt::get_self<::Instance>(uwpInstance)) {
         return self->GetOmmerOmstamce()'
}

Comment (ZihanChen-MSFT) [reply vnext/ReactUWP/TurboModule/TurboModuleUtils.cpp]: I've tested it works, and @acoates-ms suggests me to do this. May I know the reason please?

Comment (ZihanChen-MSFT) [reply vnext/ReactUWP/TurboModule/TurboModuleUtils.cpp]: Meanwhile I will update it to use get_self and see if it works.

Comment (acoates-ms) [reply vnext/ReactUWP/TurboModule/TurboModuleUtils.cpp]: I'll defer to CanHua about cppwinrt usage.  My knowledge of it is limited. (and probably largely out of date)

Comment (licanhua) [reply vnext/ReactUWP/TurboModule/TurboModuleUtils.cpp]: c++/winrt has a lot of benefit over WRL and we don't need to handle pointer and check hr code anymore.
currently ABI header(idl files in ReactUWP\ABI) and cppwinrt headers co-exists in react-uwp project.
Ideally we should only use c++/winrt in ReactUWP project, and migrate all [wrl to c++/winrt](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/move-to-winrt-from-wrl).

I hacked the project to generate ABI/Instance_rt.h, but you expect there is no ABI/Instance_rt.h in the very near future.
```
    <Midl Include="ABI\idl\ReactUWPABI.idl">
      <!-- Enable Windows Runtime ABI header files. when /reference is passed to midl.exe, the ABI head includes headers like Windows.AI.MachineLearning.MachineLearningContract.h 
      which doesn't exist actually in SDK. To workaround the problem, DisableReferences is enabled to disable /reference.      
       -->
      <DisableReferences>true</DisableReferences>
      <HeaderFileName>$(IdlHeaderDirectory)\%(Filename).h</HeaderFileName>
      <MetadataFileName>$(UnmergedWinmdDirectory)\%(Filename).winmd</MetadataFileName>
      <AdditionalOptions>
      </AdditionalOptions>
    </Midl>
```

File: vnext/ReactUWP/ReactUWP.vcxproj.filters [hunk 2]
```diff
@@ -627,6 +630,10 @@
     <ClInclude Include="Utils\ResourceBrushUtils.h">
       <Filter>Utils</Filter>
     </ClInclude>
+    <ClInclude Include="Utils\StandardControlResourceKeyNames.h" />
```
Comment (licanhua) [inline vnext/ReactUWP/ReactUWP.vcxproj.filters]: Do you forgot to check in StandardControlResourceKeyNames.h or it's in other project?

**Comment by JunielKatarn** [comment]
> > Why `GetFacebookReactInstance` and not `GetReactInstance`?
> 
> I am going to say `facebook::react::Instance` in this way. `GetReactInstance` could also mean `react::uwp::Instance`.

In my humble opinion, if `facebook::react::Instance` is the core and fundamental type, it should be the one referred to with the `GetReactInstance` getter.
The UWP instance should likely be accessed with the name `GetUwpInstance`.

**Comment by matthargett** [comment]
Could this be a template return value so the caller can get whichever is appropriate without creating C-style method naming overloads?

Side question: are there plans to push some WinRT instance things into FB’s Instance? If so, would it make sense to have WinRT Instance derive instead of just encapsulate?

**Comment by ZihanChen-MSFT** [comment]
> > > Why `GetFacebookReactInstance` and not `GetReactInstance`?
> > 
> > 
> > I am going to say `facebook::react::Instance` in this way. `GetReactInstance` could also mean `react::uwp::Instance`.
> 
> In my humble opinion, if `facebook::react::Instance` is the core and fundamental type, it should be the one referred to with the `GetReactInstance` getter.
> The UWP instance should likely be accessed with the name `GetUwpInstance`.

Thank you for your comment, I will consider it.

**Comment by ZihanChen-MSFT** [comment]
> Could this be a template return value so the caller can get whichever is appropriate without creating C-style method naming overloads?
> 
> Side question: are there plans to push some WinRT instance things into FB’s Instance? If so, would it make sense to have WinRT Instance derive instead of just encapsulate?

I don't know, but the WinRT instance is required to be recognizable by WinRT, which means it should be a COM implementation. It could be difficult to do it in this way.

File: packages/react-native-win32/just-task.js [hunk 3]
```diff
@@ -95,6 +95,7 @@ task(
     'copyFlowFiles',
     'copyPngFiles',
     'ts',
+    'flow-check',
```
Comment (acoates-ms) [inline packages/react-native-win32/just-task.js]: This looks like a bad merge. -- Please remove this again.

File: vnext/just-task.js [hunk 4]
```diff
@@ -76,6 +76,7 @@ task(
     'initRNLibraries',
     'copyFlowFiles',
     'ts',
+    'flow-check',
```
Comment (acoates-ms) [inline vnext/just-task.js]: Bad merge -- remove

File: vnext/ReactUWP/TurboModule/TurboModuleUtils.cpp (hunk 1 above)
Comment (ZihanChen-MSFT) [reply vnext/ReactUWP/TurboModule/TurboModuleUtils.cpp]: Tried `get_self<ABI::react::uwp::Instance>` but it gives me an error
```
'abi_GetTrustLevel': is not a member of 'ABI::react::uwp::Instance'
```

And I failed to find any sub class of this class. Do you know why this error get prompted? Is there any missing piece for this implementation class to be a C++/WinRT qualified class? Or do you think the old way is acceptable?

Comment (acoates-ms) [reply vnext/ReactUWP/TurboModule/TurboModuleUtils.cpp]: @licanhua

File: vnext/ReactUWP/TurboModule/TurboModuleUtils.cpp [hunk 5]
```diff
@@ -0,0 +1,22 @@
...
+#include "../ABI/Instance_rt.h"
+
+namespace react::uwp {
+
+std::shared_ptr<facebook::react::Instance> __cdecl GetReactInstanceFromUwpInstance(
+    const winrt::react::uwp::Instance &uwpInstance) {
+  winrt::com_ptr<ABI::react::uwp::IInstance> abiIInstance;
+  winrt::copy_to_abi(uwpInstance, *abiIInstance.put_void());
+  assert(abiIInstance);
+  ABI::react::uwp::Instance *abiInstance = static_cast<ABI::react::uwp::Instance *>(abiIInstance.get());
```
Comment (licanhua) [inline vnext/ReactUWP/TurboModule/TurboModuleUtils.cpp]: From https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/interop-winrt-abi#unsafe-interop-with-abi-com-interface-pointers, below code may work
```
abiInstance = reinterpret_cast<ABI::react::uwp::Instance*>(get_abi(uwpInstance));
```
Also please do hr result check and null check if needed:
example to check hr result:
```
winrt::check_result(ptr.query_to(winrt::guid_of<To>(), winrt::put_abi(result)));
```

Example to check null:
if (auto reactInstance = abiInstance->getInstance()) {
    return reactInstance->GetInnerInstance();
}

File: vnext/ReactUWP/TurboModule/TurboModuleUtils.cpp (hunk 1 above)
Comment (licanhua) [reply vnext/ReactUWP/TurboModule/TurboModuleUtils.cpp]: Look like we need to convert Instance from WRL to cppwinrt first. so you can ignore it.

File: vnext/ReactUWP/TurboModule/TurboModuleUtils.cpp [hunk 6]
```diff
@@ -0,0 +1,21 @@
...
+#include <TurboModuleUtils.h>
+#include "../ABI/Instance_rt.h"
+
+namespace react::uwp {
+
+std::shared_ptr<facebook::react::Instance> __cdecl GetReactInstanceFromUwpInstance(
+    const winrt::react::uwp::Instance &uwpInstance) {
+  auto abiInstance = reinterpret_cast<ABI::react::uwp::Instance *>(winrt::get_abi(uwpInstance));
+  auto reactInstance = abiInstance->getInstance();
+  assert(reactInstance);
```
Comment (licanhua) [inline vnext/ReactUWP/TurboModule/TurboModuleUtils.cpp]: Personally I prefer if-else over assert.

File: vnext/ReactUWP/TurboModule/TurboModuleUtils.cpp [hunk 7]
```diff
@@ -0,0 +1,21 @@
...
+  auto fbInstance = reactInstance->GetInnerInstance();
```
Comment (licanhua) [inline vnext/ReactUWP/TurboModule/TurboModuleUtils.cpp]: return reactInstance->GetInnerInstance();

File: vnext/ReactUWP/TurboModule/TurboModuleUtils.cpp (hunk 6 above)
Comment (ZihanChen-MSFT) [reply vnext/ReactUWP/TurboModule/TurboModuleUtils.cpp]: I think it's fine, it can't fail, or it is a bug. So I prefer to crash.

File: vnext/ReactUWP/TurboModule/TurboModuleUtils.cpp (hunk 7 above)
Comment (ZihanChen-MSFT) [reply vnext/ReactUWP/TurboModule/TurboModuleUtils.cpp]: Close this since duplicate
