### PR TITLE
Disable warning 4103 in MemoryMappedBufferTests.cpp

### PR DESCRIPTION
**Pull request by JunielKatarn**
Desktop solution fails to build on Visual Studio `16.9.0` with the current master as follows:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\system_error(18,1): error C2220: the following warning is treated as an error [vnext\Desktop.UnitTests\React.Windows.Desktop.UnitTests.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\system_error(18,1): warning C4103: alignment changed after including header, may be due to missing #pragma pack(pop) [vnext\Desktop.UnitTests\React.Windows.Desktop.UnitTests.vcxproj]
```

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows/pull/7319)

### CODE REVIEW

**Review by dannyvv — APPROVED** [review]

**Comment by rectified95** [comment]
Should we add a task to figure it out and restore this warning?

**Comment by asklar** [comment]
@JunielKatarn can you backport this to 0.64 please?
